Laboratorium 3 - App-ns/Controllers/ContactController.cs
using Laboratorium_3___App_ns.Models.ContactModel;
using Laboratorium_3___App_ns.Models.PCCreator;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_3___App_ns.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;

        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        public IActionResult Index()
        {
            return View(_contactService.FindAll());
        }

        // zwracanie formularza dodawania kontaktu
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contact model)
        {
            if (ModelState.IsValid)
            {
                // zapamiętanie kontaktu - modelu
                _contactService.Add(model);
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Details(int id)
        {
            return View("Details", _contactService.FindById(id));
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            return View(_contactService.FindById(id));
        }

        [HttpPost]
        public IActionResult Update(Contact contact)
        {
            if(ModelState.IsValid)
            {
                _contactService.Update(contact);
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Delete(int id)
        {
            _contactService.RemoveById(id);
            return RedirectToAction("index");
        }
    }
}

Laboratorium 3 - App-ns/Controllers/PCCreatorController.cs
using Laboratorium_3___App_ns.Models.PCCreator;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_3___App_ns.Controllers
{
    public class PCCreatorController : Controller
    {
        private readonly IPCCreatorService _pcCreatorService;

        public PCCreatorController(IPCCreatorService pcCreatorService)
        {
            _pcCreatorService = pcCreatorService;
        }

        public IActionResult Index()
        {
            return View(_pcCreatorService.GetAll());
        }

        [HttpGet]        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PC pc)
        {
            if (ModelState.IsValid)
            {
                _pcCreatorService.Add(pc);
                return RedirectToAction("Index");
            }
            else
            {
                SetValidationClasses();

                // Zwróć ten sam widok z aktualnym modelem do poprawy
                return View(pc);
            }
        }

        public IActionResult Details(int id)
        {
            return View(_pcCreatorService.FindById(id));
        }

        public IActionResult Delete(int id)
        {
            _pcCreatorService.Delete(id);
            return RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_pcCreatorService.FindById(id));
        }

        [HttpPost]
        public IActionResult Edit(PC pc)
        {
            if (ModelState.IsValid)
            {
                _pcCreatorService.Update(pc);
                return RedirectToAction("Index");
            }
            else
            {
                 SetValidationClasses();

                // Zwróć ten sam widok z aktualnym modelem do poprawy
                return View(pc);
            }
        }
        
        private void SetValidationClasses()
        {
            foreach (var key in ModelState.Keys)
            {
                // Ustaw klasę na 'is-invalid' lub 'is-valid' w zależności od stanu walidacji pola
                var errorCount = ModelState[key].Errors.Count;
                ViewData[key + "Class"] = errorCount > 0 ? "is-invalid" : "is-valid";
            }
        }

    }
}

Laboratorium 3 - App-ns/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium_3___App_ns</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium_3___App_ns.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium_3___App_ns</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Kontakty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PCCreator" asp-action="Index">Zestaw PC</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorium_3___App_ns - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</body>
</html>