Laboratorium 2/Models/BirthModel.cs
namespace Laboratorium_2.Models
{
    public class BirthModel
    {
        public DateTime BirthDate { get; set; }
        public string Name { get; set; }

        public bool IsValid()
        {
            return (BirthDate != null && Name != null) && BirthDate < DateTime.Now;
        }

        public int CalculateAge() => (DateTime.Now - BirthDate).Days / 365;

    }
}

Laboratorium 2/Models/Calculator.cs
using System.Security.Cryptography.X509Certificates;

namespace Laboratorium_2.Models
{
    public class Calculator
    {
        public double A { get; set; }
        public double B { get; set; }
        public Operators Operator { get; set; }

        public bool IsValid()
        {
            return A != null && B != null && Operator != null;
        }

        public double Calculate()
        {
            switch (Operator)
            {
                case Operators.add:
                    return (double)(A + B);
                case Operators.sub: 
                    return (double)(A - B);
                case Operators.mul:
                    return (double)(A * B);
                case Operators.div:
                    return (double)(A / B);
                default:
                    return double.NaN;
            }
        }

        public string GetStringOperator()
        {
            switch (Operator)
            {
                case Operators.add:
                    return "+";
                case Operators.sub:
                    return "-";
                case Operators.mul:
                    return "*";
                case Operators.div:
                    return "/";
                default:
                    return "Wrong operator";
            }
        }
    }
}

Laboratorium 2/Models/ErrorViewModel.cs
namespace Laboratorium_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Laboratorium 2/Models/Operators.cs
namespace Laboratorium_2.Models
{
    public enum Operators
    {
        add, sub, mul, div
    }
}

Laboratorium 2/Controllers/BirthController.cs
using Laboratorium_2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_2.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BirthForm()
        {
            return View();
        }

        public IActionResult BirthResult(BirthModel birthModel)
        {
            if (!birthModel.IsValid())
                return View("Error");

            return View(birthModel);
        }


    }
}

Laboratorium 2/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratorium_2.Models;

namespace Laboratorium_2.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Form()
        {
            return View();
        }

        public IActionResult Result(Calculator calc)
        {
            if (!calc.IsValid())
                return BadRequest();

            return View(calc);
        }
    }
}

Laboratorium 2/Controllers/HomeController.cs
using Laboratorium_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorium_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Laboratorium 2/Views/Birth/BirthForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form action="BirthResult" method="get">
    <label>Birth date:  </label>
    <input type="date" name="birthDate"/>

    <label>Name: </label>
    <input type="string" name="name" />

    <button type="submit">Send</button>
</form>

Laboratorium 2/Views/Birth/BirthResult.cshtml
@model BirthModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<p>
    Cześć @Model.Name, masz @Model.CalculateAge() lat.
</p>

Laboratorium 2/Views/Calculator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form action="Result" method="get">
    <input type="number" name="a" steep="0.0001"/>
    <select name="op">
        <option value="add">+</option>
        <option value="sub">&minus;</option>
        <option value="mul">&times;</option>
        <option value="div">&divide;</option>
    </select>
    <input type="number" name="b" steep="0.0001" />
    <button type="submit">Calculate</button>
</form>

Laboratorium 2/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<p>
    @Model.A @Model.GetStringOperator() @Model.B = @Model.Calculate()
</p>

Laboratorium 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="BirthForm">CalculateAge</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorium_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>